"
"               ██
"               ▀▀
"  ██▄  ▄██   ████     ████▄██▄   ██▄████   ▄█████▄
"   ██  ██      ██     ██ ██ ██   ██▀      ██▀    ▀
"   ▀█▄▄█▀      ██     ██ ██ ██   ██       ██
"    ████    ▄▄▄██▄▄▄  ██ ██ ██   ██       ▀██▄▄▄▄█
"     ▀▀     ▀▀▀▀▀▀▀▀  ▀▀ ▀▀ ▀▀   ▀▀         ▀▀▀▀▀
" 

set rtp+=$XDG_CONFIG_HOME/vim
set rtp+=$XDG_CACHE_HOME/vim

" automatically install the plugin manager on start
let data_dir = has('nvim') ? stdpath('data') . '/site' : "$XDG_CACHE_HOME/" . 'vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin(data_dir)
Plug 'christoomey/vim-tmux-navigator'
call plug#end()

autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal! g`\"" |
      \ endif

"enable syntax highlighting
syntax on

"disable ex mode
map Q <Nop> 

set mouse=a "mouse integration between tmux

set number "show the line numbers

set noswapfile
set nocompatible

set hlsearch "highlight the search results

set clipboard+=unnamedplus,unnamed
set tags=tags;/

set tabstop=2 softtabstop=2 shiftwidth=2
set expandtab
set number ruler
set autoindent smartindent
syntax enable
filetype plugin indent on

"automatically format python code on save
if executable("black")
  function PyFormatBuffer()
    if &modified
      let cursor_pos = getpos('.')
      :%!black -q -
      call setpos('.', cursor_pos)
    endif
  endfunction
  autocmd BufWritePre *.py :call PyFormatBuffer()
endif

"automatically format cpp code on save
if executable("clang-format")
  function CppFormatBuffer()
    if &modified && !empty(findfile('.clang-format', expand('%:p:h') . ';'))
      let cursor_pos = getpos('.')
      :%!clang-format
      call setpos('.', cursor_pos)
    endif
  endfunction
  autocmd BufWritePre *.h,*.hpp,*.c,*.cpp :call CppFormatBuffer()
endif

autocmd FileType c,cpp,java,php,tex,py,sh autocmd BufWritePre <buffer> %s/\s\+$//e
